apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metroc

labels:
  - pairs:
      app.kubernetes.io/part-of: metroc-kubernetes
      app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - nginx/deployment.yaml
  - nginx/service.yaml
  - helloapp/deployment.yaml
  - helloapp/service.yaml
