apiVersion: v1
kind: Namespace
metadata:
  name: metroc
  labels:
    app.kubernetes.io/part-of: metroc-kubernetes
    # Reject pods that don't meet the "restricted" Pod Security Standard
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
